# Generated by Django 3.1.7 on 2021-04-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_id',
            field=models.CharField(default=18201000, max_length=8),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_age',
            field=models.IntegerField(db_column='Age', default=0, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_firstname',
            field=models.CharField(db_column='First name', default='John', max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_lastname',
            field=models.CharField(db_column='Last name', default='Doe', max_length=20, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_occupation',
            field=models.CharField(db_column='Occupation', default='None', max_length=50, verbose_name='Occupation'),
        ),
    ]
