# Generated by Django 3.1.7 on 2021-04-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20210409_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_id',
            field=models.CharField(default=18201000, max_length=8, verbose_name='User ID'),
        ),
    ]
