# Generated by Django 3.1.7 on 2022-03-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20210410_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_id',
            field=models.CharField(default=18201000, max_length=8, unique=True, verbose_name='User ID'),
        ),
    ]
