# Generated by Django 3.2.7 on 2022-10-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20221005_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='course_userid',
            field=models.CharField(default=18201000, max_length=8, verbose_name='User ID'),
        ),
    ]
